### ISSUE TITLE
Pre-download of mandatory DBs

### ISSUE THREAD

**Issue by jhayer** [jhayer/baargin#3]
We need to prepare a script for downloading the following databases:
- PlasmidFinder: see install instructions there: https://bitbucket.org/genomicepidemiology/plasmidfinder/src/master/
But basically this: 
`git clone https://bitbucket.org/genomicepidemiology/plasmidfinder_db.git`

- CARD: January 2023 release: https://card.mcmaster.ca/download/0/broadstreet-v3.2.6.tar.bz2
The card.json is the file to keep for the workflow
https://card.mcmaster.ca/latest/data => for automatic download, check if it works with wget
info there: https://card.mcmaster.ca/download (CARD Data)

- Minikraken: coming soon

**Comment by Juke34** [comment]
la db plasmidfinder c'est bien `https://bitbucket.org/genomicepidemiology/plasmidfinder/src/master/test/database/enterobacteriaceae.fsa` ?
